backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "artworks"
    label: "Eserler"
    folder: "artworks"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} (ID: {{id}})" # Eser başlığı ve ID'sini listede göster
    fields:
      - { label: "Eser ID", name: "id", widget: "string" }
      - { label: "Kategori", name: "category", widget: "select", options: ["resim", "heykel"] }
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Açıklama (TR)", name: "description_tr", widget: "string" }
      - { label: "Açıklama (EN)", name: "description_en", widget: "string" }
      - { label: "Malzeme (TR)", name: "material_tr", widget: "string" }
      - { label: "Malzeme (EN)", name: "material_en", widget: "string" }
      - { label: "Boyut (TR)", name: "size_tr", widget: "string" }
      - { label: "Boyut (EN)", name: "size_en", widget: "string" }
      - { label: "Ana Görsel", name: "main_image", widget: "image" }
      - { label: "Detay Görsel 1", name: "detail_image1", widget: "image", required: false }
      - { label: "Detay Görsel 2", name: "detail_image2", widget: "image", required: false }
